[phases.setup]
aptPkgs = ["hugo"]

[phases.build]
cmds = ["hugo --minify --config hugo.toml"]

[phases.deploy]

[ environment ]
HUGO_VERSION = "0.145.0"

[ nixpacks.included_files ]
paths = ["/public"]
